trigger:
  branches:
    include:
      - main

pr: none

pool:
  name: 'DevopsDemo'

variables:
  buildConfiguration: 'Release'
  imageRepository: 'chinni232/helloworld-api'
  dockerRegistryServiceConnection: 'dockerhub-service-connection'
  imageTag: '$(Build.BuildId)'

stages:
- stage: Build_Test
  displayName: Build and Test
  jobs:
  - job: BuildTest
    displayName: Restore Build Test
    steps:
    - task: UseDotNet@2
      displayName: Install .NET 9 SDK
      inputs:
        packageType: 'sdk'
        version: '9.0.x'

    - script: dotnet restore src/HelloWorld.Api/HelloWorld.Api.csproj
      displayName: Restore API

    - script: dotnet build src/HelloWorld.Api/HelloWorld.Api.csproj --configuration $(buildConfiguration) --no-restore
      displayName: Build API

    - script: dotnet test tests/HelloWorld.UnitTests/HelloWorld.UnitTests.csproj --configuration $(buildConfiguration) --no-build
      displayName: Run Unit Tests

    - script: dotnet test tests/HelloWorld.IntegrationTests/HelloWorld.IntegrationTests.csproj --configuration $(buildConfiguration) --no-build
      displayName: Run Integration Tests

- stage: Docker_Build_Push
  displayName: Docker Build and Push
  dependsOn: Build_Test
  condition: succeeded()
  jobs:
  - job: DockerBuildPush
    displayName: Build and Push Docker Image
    steps:
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(imageTag)
          latest